---
platform: linux

rootfs_uri: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: deployments-persi
  - name: cephfs-bosh-release
  - name: cf-release

outputs:
  - name: generated-manifest-ceph

params:
  DEPLOYMENTS_DIR: ~
  ENVIRONMENT_NAME: ~
  INFRASTRUCTURE: ~
  USE_GARDEN_RUNC: true
  PATS_BROKER_USERNAME: ~
  PATS_BROKER_PASSWORD: ~

run:
  path: cephfs-bosh-release/scripts/ci/generate_deployment_manifests
