name: cephfs
director_uuid: (( merge ))

releases:
  - name: cephfs
    version: latest

jobs:
  - name: cephbroker-acc
    instances: 1
    resource_pool: ceph-resourcepool
    networks:
    - name: ceph-net
      static_ips: &web-ips [10.244.8.2]
    properties:
      route_registrar:
        routes:
          - name: cephbroker-acc
            port: 8999
            registration_interval: 20s
            tags:
              component: cephbroker
            uris:
            - cephbroker2.persi.cf-app.com
      cephbroker:
        service-name: cephbroker-acc
        service-id: cephbroker-acc
        plan-name: free-acc
        plan-id: free-acc-plan-guid
        plan-desc: free ceph filesystem for acceptance testing
    templates:
    - release: cephfs
      name: cephbroker
    - release: cf
      name: route_registrar
    log_level: debug

properties:
  cephbroker: (( merge ))

networks:
  - name: ceph-net
    type: manual
    subnets:
      - range: 10.244.8.0/24
        gateway: 10.244.8.1
        static: *web-ips
        cloud_properties: {}

resource_pools:
  - name: ceph-resourcepool
    network: ceph-net
    cloud_properties: {}
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest

compilation:
  workers: 1
  network: ceph-net
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
