---
# All variables are defined in the inventory (or group_vars), so you can test
# this playbook offline with a fake inventory, or reuse in other places

- name: start
  hosts: localhost
  gather_facts: False
  serial: 1

  tasks:
    - include: start.yml